import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { assertTestCaseId, TEST_CASE_ID_PATTERN } from './testCaseId.js';

export interface TcIdCatalogEntry {
  id: string;
  title: string;
  status: string;
}

export function testCaseIdToCatalogKey(testCaseId: string): string {
  assertTestCaseId(testCaseId);
  return testCaseId.replace(/-/g, '_');
}

export function catalogKeyToTestCaseId(catalogKey: string): string | null {
  const match = catalogKey.match(/^TC_(UT|ITa|ITb|ST|UAT)_(\d{4})(?:_(\d{2}))?$/);
  if (!match) return null;
  const split = match[3] ? `-${match[3]}` : '';
  const candidate = `TC-${match[1]}-${match[2]}${split}`;
  return TEST_CASE_ID_PATTERN.test(candidate) ? candidate : null;
}

export function listTestCaseDocEntries(testCasesDir: string): TcIdCatalogEntry[] {
  const entries: TcIdCatalogEntry[] = [];
  if (!fs.existsSync(testCasesDir)) return entries;

  for (const name of fs.readdirSync(testCasesDir).sort()) {
    if (!name.startsWith('TC-') || !name.endsWith('.md')) continue;
    const filePath = path.join(testCasesDir, name);
    const raw = fs.readFileSync(filePath, 'utf8');
    const { data } = matter(raw);
    const id = String(data.id ?? '').trim();
    if (!TEST_CASE_ID_PATTERN.test(id)) continue;
    entries.push({
      id,
      title: String(data.title ?? '').trim() || id,
      status: String(data.status ?? 'draft').trim(),
    });
  }

  return entries;
}

function escapeBlockComment(text: string): string {
  return text.replace(/\*\//g, '* /');
}

export function renderTcIdCatalogModule(entries: readonly TcIdCatalogEntry[]): string {
  const lines: string[] = [
    '/**',
    ' * TraceWeave test-case ID catalog for editor IntelliSense.',
    ' * Generated by scripts/generate-tc-id-catalog.ts — do not edit.',
    ' */',
    '',
    '/** @internal Use {@link formalTestTitle} with these values in `test(...)`. */',
    'export const TC_IDS = {',
  ];

  for (const entry of entries) {
    const key = testCaseIdToCatalogKey(entry.id);
    const hint = escapeBlockComment(entry.title);
    lines.push(`  /** ${entry.id} — ${hint} (${entry.status}) */`);
    lines.push(`  ${key}: '${entry.id}',`);
  }

  lines.push('} as const;', '', 'export type CatalogTestCaseId = (typeof TC_IDS)[keyof typeof TC_IDS];', '');
  return lines.join('\n');
}

export function buildTcIdCatalogSource(testCasesDir: string): string {
  return renderTcIdCatalogModule(listTestCaseDocEntries(testCasesDir));
}
